// SystemVerilog module to generate a rectangular wave using a Look-Up Table (LUT)
// Signals generated by Idea Artur

module lut_rectangular #(
  int OUT_WIDTH = 16,           // Width of the output data (default: 16 bits)
  int LUT_SIZE = 32,             // Size of the Look-Up Table (default: 32 entries)
  int SEL_WIDTH = $clog2(LUT_SIZE) // Width of the Look-Up Table selector (calculated as log2 of LUT size)
) (
  input logic clk,               // Input clock signal
  input logic rst,               // Input reset signal
  input logic [SEL_WIDTH-1:0] index,     // Selector to access the Look-Up Table
  input logic [SEL_WIDTH-1:0] duty_cycle, // Duty cycle of the rectangular wave
  output logic [OUT_WIDTH-1:0] rectangular // Output of the rectangular wave value
);

// Always block sensitive to the rising edge of the clock signal
always_ff @(posedge clk) begin
  if (~rst) begin
      rectangular <= 0; // If the reset signal is active, set the output to zero
    end else begin
        // Logic to generate the rectangular wave based on the selector and duty cycle
      rectangular <= (index < duty_cycle) ? 16'sd32767 : -16'sd32767;
        // If lut_sel is less than duty_cycle, the output is 32767, otherwise it is -32767
    end
end

endmodule